name: Publish

on: 
  push:
    tags:
      - '*'

jobs: 
  publish:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install
        run: npm install

      - name: build:render
        run: npm run build:render

      - name: build:main
        run: npm run build:main
        
      - name: publish
        env:
          bucket: ${{ secrets.bucket }}
          accessKeyId: ${{ secrets.accessKeyId }}
          accessKeySecret: ${{ secrets.accessKeySecret }}
        run: npm run upload:oss
